language: ruby
install:
- bundle install
script: bundle exec rake site:deploy
#global:
  #env:
    #- "GIT_NAME=jmarlena"
    #- "GIT_EMAIL=jmarlena.canepa@gmail.com"
    #- "GIT_TOKEN=d000000000000000000000000"
    #secure: 00000000000000000
